Simplify allocator
tracel-ai/cubecl pull request #388
Opened 2024-12-20 16:42 UTC by maxtremblay

This is a big one.

### Highlights

- The allocator implementation is simpler.
- The benchmark results are similar.
- I discovered and fixed a few bugs.

### Allocator refactor

- Remove the allocator trait and its two implementations in favor of a single allocator struct.
- Rename the local variable creations to new named closer to rust naming scheme (example, use mut for mutable variables).
- Rename the variant in `VariableKind` to match the changes.
- Propagate the changes. This explains the large amount of modified files. A lot of it is renaming and changing to the new allocator.
- Document to allocator struct. 

### Changing the backends

- Rename the local variable variant of the `Variable` enum to match `cubecl-core`.
- Add the `depth` field to `LocalVariable`.
- All local immutable variables are now named `l_{depth}_{id}`.
- All local mutable variables (including restricted) are now named `l_mut_{depth}_{id}`.

### Allocation strategy

- In a few expand functions, I replaced the use of a mutable variable with an immutable one. 

### Discovered bugs

With all the above changes, I discovered a few bugs in cubecl that I fixed.

- Because the reusing allocator (used by cuda) was not doing any distinction between mutable and immutable variables, we often used immutable variables when we should have used mutable one. Mostly for accumulators in plane operations.
- Fix an issue with line indexing where elements of the line where tagged with a vectorization > 1 while there are scalar. Before, we were lucky enough for this bug to have no effect (wgpu: inference let us avoid the type during declaration. cpp: we were using mutables everywhere before which were not causing an error, but were wastefully declared as vectorized).
- There were some missing `fmt_left` in the cpp backend.
 
### Benchmarks

There are no statistically meaningful changes.

[bench_cuda_main.txt](https://github.com/user-attachments/files/18213122/bench_cuda_main.txt)
[bench_cuda_new_alloc.txt](https://github.com/user-attachments/files/18213123/bench_cuda_new_alloc.txt)
[bench_wgpu_main.txt](https://github.com/user-attachments/files/18213124/bench_wgpu_main.txt)
[bench_wgpu_new_alloc.txt](https://github.com/user-attachments/files/18213125/bench_wgpu_new_alloc.txt)

2024-12-20 17:56 UTC, nathanielsimard commented on crates/cubecl-core/src/ir/operation.rs
> +    let item = scope.create_local_mut(out.item);
Is mut necessary?

2024-12-20 17:56 UTC, nathanielsimard commented on crates/cubecl-core/src/ir/operation.rs
> +    let inside_bound = scope.create_local_mut(Item::new(Elem::Bool));
Is mut necessary?

2024-12-20 17:56 UTC, nathanielsimard commented on crates/cubecl-core/src/ir/scope.rs
> +        let local = self.create_local_mut(item);
Is mut necessary?

2024-12-20 17:56 UTC, nathanielsimard commented on crates/cubecl-core/src/ir/scope.rs
> +        let local = self.create_local_mut(item);
Is mut necessary?

2024-12-20 18:52 UTC, maxtremblay commented on crates/cubecl-core/src/frontend/plane.rs
> +        let output = context.create_local_mut(elem.item);
In fact, it is an issue with the planeAny implementation of cuda. I will fix it.

2024-12-21 21:06 UTC, nathanielsimard requested changes

2024-12-21 21:06 UTC, nathanielsimard commented on crates/cubecl-core/src/frontend/container/line/base.rs
> +                        let output = context.create_local_mut(Item::vectorized(bool::as_elem(), size));
I don't think this needs to be mut?

2024-12-21 21:06 UTC, nathanielsimard commented on crates/cubecl-core/src/frontend/container/line/base.rs
> +            let output = context.create_local(Item::vectorized(P::as_elem(), length));
Is mut required?

2024-12-21 21:06 UTC, nathanielsimard commented on crates/cubecl-core/src/frontend/operation/base.rs
> +    let output = context.create_local_mut(out_item);
Is mut required?

2024-12-21 21:06 UTC, nathanielsimard commented on crates/cubecl-cpp/src/shared/instruction.rs
> +            let maybe_const = if out.is_const() { " cosnt" } else { "" };
typo: `cosnt`

2024-12-21 21:06 UTC, nathanielsimard commented on crates/cubecl-cpp/src/shared/warp.rs
> +        let maybe_const = if input.is_const() { " const" } else { "" };
We could have a method for that, it's repeated at multiple places.

2024-12-21 21:06 UTC, nathanielsimard commented on crates/cubecl-cuda/tests/main.rs
> +    // write!(file, "{compiled}").unwrap();
deadcode

2024-12-21 21:06 UTC, nathanielsimard commented on crates/cubecl-cuda/tests/main.rs
> +    // write!(file, "{compiled}").unwrap();
Deadcode

2024-12-21 21:06 UTC, nathanielsimard commented on crates/cubecl-cuda/tests/main.rs
> +    // write!(file, "{compiled}").unwrap();
deadcode

2024-12-21 21:06 UTC, nathanielsimard commented on crates/cubecl-cuda/tests/main.rs
> +    // write!(file, "{compiled}").unwrap();
deadcode

2024-12-21 21:06 UTC, nathanielsimard commented on crates/cubecl-cuda/tests/main.rs
> +    // write!(file, "{compiled}").unwrap();
deadcode

2024-12-21 21:06 UTC, nathanielsimard commented on crates/cubecl-cuda/tests/main.rs
> +    // write!(file, "{compiled}").unwrap();
deadcode

2024-12-21 21:06 UTC, nathanielsimard commented on crates/cubecl-wgpu/tests/main.rs
> +// use std::io::Write;
deadcode

2024-12-21 21:06 UTC, nathanielsimard commented on crates/cubecl-wgpu/tests/main.rs
> +    // write!(file, "{compiled}").unwrap();
deadcode

2024-12-21 21:06 UTC, nathanielsimard commented on crates/cubecl-wgpu/tests/main.rs
> +    // write!(file, "{compiled}").unwrap();
deadcode

2024-12-21 21:06 UTC, nathanielsimard commented on crates/cubecl-wgpu/tests/main.rs
> +    // write!(file, "{compiled}").unwrap();
deadcode

2024-12-21 21:06 UTC, nathanielsimard commented on crates/cubecl-wgpu/tests/main.rs
> +    // write!(file, "{compiled}").unwrap();
deadcode

2024-12-21 21:06 UTC, nathanielsimard commented on crates/cubecl-wgpu/tests/main.rs
> +    // write!(file, "{compiled}").unwrap();
deadcode

2024-12-21 21:06 UTC, nathanielsimard commented on crates/cubecl-wgpu/tests/main.rs
> +    // write!(file, "{compiled}").unwrap();
deadcode

2024-12-21 21:06 UTC, nathanielsimard commented on crates/cubecl-wgpu/tests/main.rs
> +    // write!(file, "{compiled}").unwrap();
deadcode

2025-01-06 18:46 UTC, nathanielsimard approved these changes

2025-01-06 18:53 UTC, merged